<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 8/02/2017
 * Time: 2:12 PM
 */
define('PATH_SITE_BASE', dirname(__DIR__).DIRECTORY_SEPARATOR);
include('../system/config/config.php');
$start_stamp = microtime(1);
echo '<pre>';

// TEST IMAGE ENTITY
//$row = [
//    ['name'=>'Bouquet','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-238.JPG'],
//    ['name'=>'Arrangement','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-218.JPG'],
//    ['name'=>'New Born','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-013a.JPG'],
//    ['name'=>'Sympathy','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-07-02_001.JPG'],
//    ['name'=>'Wedding','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0031.JPG'],
//    ['name'=>'Artificial','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_006.JPG'],
//    ['name'=>'Fruit Hamper','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/wagga-florist-010a.JPG'],
//    ['name'=>'Gift Ideas','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2015-07-14_011.jpg']
//];
//$row = [
//    ['name'=>'B633','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2015-01-29_006.JPG']
//];
//$row = [
//    ['name'=>'B344','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-001c.JPG']
//];
//$row = [
//    ['name'=>'B344','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-001c.JPG']
//];
$row = [
//    ['name'=>'B633','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2015-01-29_006.JPG'],
//    ['name'=>'B344','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-001c.JPG'],
//    ['name'=>'B557','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/4wagga-florist_002.JPG'],
//    ['name'=>'B647','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2015-02-06_006.JPG'],
//    ['name'=>'B738','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist_33_.JPG'],
//    ['name'=>'B729','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/12-16_6_.JPG'],
//    ['name'=>'B731','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2-9_3_.JPG'],
//    ['name'=>'B730','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/1-15_5_.JPG'],
//    ['name'=>'B723','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/1-18_11_.JPG'],
//    ['name'=>'B722','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/1-18_7_.JPG'],
//    ['name'=>'B572','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist_9_.JPG'],
//    ['name'=>'B569','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist_31_.JPG'],
//    ['name'=>'B721','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/1-17_1_.JPG'],
//    ['name'=>'B624','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2014-10-22_002.JPG'],
//    ['name'=>'B326','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-059.JPG'],
//    ['name'=>'B736','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2014-07-14_002.JPG'],
//    ['name'=>'B696','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/img_0002.JPG'],
//    ['name'=>'B737','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/img_0012.JPG'],
//    ['name'=>'B732','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/3-27_6_.JPG'],
//    ['name'=>'B559','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-265b.JPG'],
//    ['name'=>'B733','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/3-31_5_.JPG'],
//    ['name'=>'B486','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-222.JPG'],
//    ['name'=>'B487','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-234.JPG'],
//    ['name'=>'B374','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-104a.JPG'],
//    ['name'=>'B485','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-216.JPG'],
//    ['name'=>'B735','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/12014-07-12_002.JPG'],
    ['name'=>'B734','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/4-10_3_.JPG'],
    ['name'=>'B561','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-063.JPG'],
    ['name'=>'B705','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2014-09-01_011.JPG'],
    ['name'=>'B370','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-088b.JPG'],
    ['name'=>'B488','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-238.JPG'],
    ['name'=>'B575','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist_83_.JPG'],
    ['name'=>'B560','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-285.JPG'],
    ['name'=>'B256','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-033.JPG'],
    ['name'=>'B594','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-014b.JPG'],
    ['name'=>'B595','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/wagga-florist-021.JPG'],
    ['name'=>'B703','source_file'=>'http://efloristwagga.com.au/assets/galleries/54/2014-12-23_007.JPG'],
//    ['name'=>'A649','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-07_007.JPG'],
//    ['name'=>'A648','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-07_005.JPG'],
//    ['name'=>'A643','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-04_002.JPG'],
//    ['name'=>'A644','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-04_004.JPG'],
//    ['name'=>'A645','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-04_005.JPG'],
//    ['name'=>'A711','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/delete.jpg'],
//    ['name'=>'A650','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-08_003.JPG'],
//    ['name'=>'A642','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/12015-01-30_012.JPG'],
//    ['name'=>'A641','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-01-30_017.JPG'],
//    ['name'=>'A551','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_009.JPG'],
//    ['name'=>'A651','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2015-02-11_009.JPG'],
//    ['name'=>'A593','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2wagga-florist_004.JPG'],
//    ['name'=>'A359','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-044.JPG'],
//    ['name'=>'A318','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-094a.JPG'],
//    ['name'=>'A406','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-076.JPG'],
//    ['name'=>'A631','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga_florist.jpg'],
//    ['name'=>'A565','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_023.JPG'],
//    ['name'=>'A356','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-009a.JPG'],
//    ['name'=>'A317','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-093a.JPG'],
//    ['name'=>'A713','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/img_0028.JPG'],
//    ['name'=>'A627','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist.JPG'],
//    ['name'=>'A321','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-108.JPG'],
//    ['name'=>'A547','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_002.JPG'],
//    ['name'=>'A588','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_015.JPG'],
//    ['name'=>'A221','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/040a.JPG'],
//    ['name'=>'A585','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/3wagga-florist_002.JPG'],
//    ['name'=>'A549','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_007.JPG'],
//    ['name'=>'A548','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_004.JPG'],
//    ['name'=>'A508','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-339.JPG'],
//    ['name'=>'A501','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-317.JPG'],
//    ['name'=>'A401','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-214a.JPG'],
//    ['name'=>'A602','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2014-05-07_004.JPG'],
//    ['name'=>'A405','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-162.JPG'],
//    ['name'=>'A205','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/035.JPG'],
//    ['name'=>'A632','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/1wagga_florist.jpg'],
//    ['name'=>'A204','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/032.JPG'],
//    ['name'=>'A681','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/img_0099.JPG'],
//    ['name'=>'A678','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/img_0111.JPG'],
//    ['name'=>'A223','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/038.JPG'],
//    ['name'=>'A403','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-218.JPG'],
//    ['name'=>'A230','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/001.JPG'],
//    ['name'=>'A235','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/048.JPG'],
//    ['name'=>'A604','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2014-05-17_004.JPG'],
//    ['name'=>'A587','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_001.JPG'],
//    ['name'=>'A320','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-087.JPG'],
//    ['name'=>'A601','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist_24_.JPG'],
//    ['name'=>'A607','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/2014-05-29_001.JPG'],
//    ['name'=>'A400','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-210a.JPG'],
//    ['name'=>'A198','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/029.JPG'],
//    ['name'=>'A597','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/5wagga-florist_002.JPG'],
//    ['name'=>'A280','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/1002.JPG'],
//    ['name'=>'A278','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-005.JPG'],
//    ['name'=>'A290','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-013.JPG'],
//    ['name'=>'A279','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-003.jpg'],
//    ['name'=>'A277','source_file'=>'http://efloristwagga.com.au/assets/galleries/55/wagga-florist-001.jpg'],
//    ['name'=>'N682','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/img_0009.JPG'],
//    ['name'=>'N676','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2015-07-17_006.JPG'],
//    ['name'=>'N238','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/008.JPG'],
//    ['name'=>'N322','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-004b.JPG'],
//    ['name'=>'N613','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2014-06-19_009.JPG'],
//    ['name'=>'N620','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2014-07-18_015.JPG'],
//    ['name'=>'N684','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2014-12-19_007.JPG'],
//    ['name'=>'N685','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/1img_0009.JPG'],
//    ['name'=>'N590','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-016.JPG'],
//    ['name'=>'N579','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist_014.JPG'],
//    ['name'=>'N715','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2014-06-28_002.JPG'],
//    ['name'=>'N615','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2014-06-20_007.JPG'],
//    ['name'=>'N274','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-004.JPG'],
//    ['name'=>'N323','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-006.JPG'],
//    ['name'=>'N464','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/6wagga-florist-010a.JPG'],
//    ['name'=>'N686','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/img_0008.JPG'],
//    ['name'=>'N520','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-013a.JPG'],
//    ['name'=>'N521','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist-013c.JPG'],
//    ['name'=>'N591','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist_003.JPG'],
//    ['name'=>'N675','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/2015-06-24_009.JPG'],
//    ['name'=>'N584','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist_006.JPG'],
//    ['name'=>'N80','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/button.jpg'],
//    ['name'=>'N83','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/baby_bkt.jpg'],
//    ['name'=>'N578','source_file'=>'http://efloristwagga.com.au/assets/galleries/56/wagga-florist_004.JPG'],
//    ['name'=>'S524','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist-347a.JPG'],
//    ['name'=>'S625','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist.JPG'],
//    ['name'=>'S532','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist-006.JPG'],
//    ['name'=>'S720','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/1-17_5_.JPG'],
//    ['name'=>'S138','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/f5.jpg'],
//    ['name'=>'S714','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/img_0023.JPG'],
//    ['name'=>'S600','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-03-03_013.JPG'],
//    ['name'=>'S166','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/swhite.jpg'],
//    ['name'=>'S137','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/f4.jpg'],
//    ['name'=>'S616','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-06-12_001.JPG'],
//    ['name'=>'S139','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/f6.jpg'],
//    ['name'=>'S599','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist_21_.JPG'],
//    ['name'=>'S523','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist-003b.JPG'],
//    ['name'=>'S679','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/img_0087.JPG'],
//    ['name'=>'S531','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist_006.JPG'],
//    ['name'=>'S567','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/1wagga-florist_006.JPG'],
//    ['name'=>'S566','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist_011.JPG'],
//    ['name'=>'S628','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-11-19_005.JPG'],
//    ['name'=>'S617','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-07-02_001.JPG'],
//    ['name'=>'S64','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/s1.jpg'],
//    ['name'=>'S726','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2014-04-10_008.JPG'],
//    ['name'=>'S333','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/wagga-florist-001a.JPG'],
//    ['name'=>'S712','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/delete.jpg'],
//    ['name'=>'S728','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/2017-2-2_3_.JPG'],
//    ['name'=>'S719','source_file'=>'http://efloristwagga.com.au/assets/galleries/57/1-18_3_.JPG'],
//    ['name'=>'W697','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0023.JPG'],
//    ['name'=>'W698','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0029.JPG'],
//    ['name'=>'W699','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0035.JPG'],
//    ['name'=>'W701','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0031.JPG'],
//    ['name'=>'W700','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0037.JPG'],
//    ['name'=>'W702','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1img_0020.JPG'],
//    ['name'=>'W690','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1img_0003.JPG'],
//    ['name'=>'W691','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1img_0004.JPG'],
//    ['name'=>'W692','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1img_0015.JPG'],
//    ['name'=>'W693','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0020.JPG'],
//    ['name'=>'W694','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0026.JPG'],
//    ['name'=>'W695','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/img_0030.JPG'],
//    ['name'=>'W663','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-04-18_008.JPG'],
//    ['name'=>'W664','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-04-18_006.JPG'],
//    ['name'=>'W665','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-04-18_015.JPG'],
//    ['name'=>'W667','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/12015-04-18_023.JPG'],
//    ['name'=>'W668','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-04-18_025.JPG'],
//    ['name'=>'W669','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-04-18_027.JPG'],
//    ['name'=>'W652','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_038.JPG'],
//    ['name'=>'W653','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_040.JPG'],
//    ['name'=>'W655','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_046.JPG'],
//    ['name'=>'W656','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_052.JPG'],
//    ['name'=>'W657','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_049.JPG'],
//    ['name'=>'W654','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2015-03-14_041.JPG'],
//    ['name'=>'W514','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/4wagga-florist-005.JPG'],
//    ['name'=>'W515','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2wagga-florist-004.JPG'],
//    ['name'=>'W516','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2wagga-florist-008.JPG'],
//    ['name'=>'W517','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/3wagga-florist-010.JPG'],
//    ['name'=>'W518','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-013.JPG'],
//    ['name'=>'W519','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1wagga-florist-014.JPG'],
//    ['name'=>'W469','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/018.JPG'],
//    ['name'=>'W470','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/019.JPG'],
//    ['name'=>'W471','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/020.JPG'],
//    ['name'=>'W473','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/024.JPG'],
//    ['name'=>'W474','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/025.JPG'],
//    ['name'=>'W475','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/032.JPG'],
//    ['name'=>'W439','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1wagga-florist-010.JPG'],
//    ['name'=>'W438','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-008.JPG'],
//    ['name'=>'W437','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1wagga-florist-007.JPG'],
//    ['name'=>'W435','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2wagga-florist-005.JPG'],
//    ['name'=>'W436','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-003.JPG'],
//    ['name'=>'W450','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-001.JPG'],
//    ['name'=>'W447','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1wagga-florist-003.JPG'],
//    ['name'=>'W448','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-002.JPG'],
//    ['name'=>'W446','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/1wagga-florist-004.JPG'],
//    ['name'=>'W443','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-007a.JPG'],
//    ['name'=>'W440','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/2wagga-florist-010.JPG'],
//    ['name'=>'W425','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-_008.JPG'],
//    ['name'=>'W426','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-_002.JPG'],
//    ['name'=>'W423','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-_006.JPG'],
//    ['name'=>'W420','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wagga-florist-004b.JPG'],
//    ['name'=>'W162','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wctr.jpg'],
//    ['name'=>'W161','source_file'=>'http://efloristwagga.com.au/assets/galleries/58/wrecp.jpg'],
//    ['name'=>'M458','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-059.JPG'],
//    ['name'=>'M457','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-054.JPG'],
//    ['name'=>'M467','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_007.JPG'],
//    ['name'=>'M468','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_003.JPG'],
//    ['name'=>'M538','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-094.JPG'],
//    ['name'=>'M312','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-030.JPG'],
//    ['name'=>'M535','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-090.JPG'],
//    ['name'=>'M481','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_014.JPG'],
//    ['name'=>'M533','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-086.JPG'],
//    ['name'=>'M480','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_008.JPG'],
//    ['name'=>'M529','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_005.JPG'],
//    ['name'=>'M477','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_013.JPG'],
//    ['name'=>'M476','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist_006.JPG'],
//    ['name'=>'M534','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-091.JPG'],
//    ['name'=>'M364','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-043.JPG'],
//    ['name'=>'M158','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/017.JPG'],
//    ['name'=>'M630','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga_florist.jpg'],
//    ['name'=>'M358','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-039b.JPG'],
//    ['name'=>'M265','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-020.JPG'],
//    ['name'=>'M360','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-045b.JPG'],
//    ['name'=>'M543','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/1wagga-florist_005.JPG'],
//    ['name'=>'M545','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/2wagga-florist_008.JPG'],
//    ['name'=>'M295','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-018a.JPG'],
//    ['name'=>'M544','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/1wagga-florist_008.JPG'],
//    ['name'=>'M296','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-012a.JPG'],
//    ['name'=>'M282','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-007a.JPG'],
//    ['name'=>'M546','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/1wagga-florist_003.JPG'],
//    ['name'=>'M283','source_file'=>'http://efloristwagga.com.au/assets/galleries/59/wagga-florist-008c.JPG'],
//    ['name'=>'F621','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2014-09-29_006.JPG'],
//    ['name'=>'F63','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/fruits04.jpg'],
//    ['name'=>'F62','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/fruits.jpg'],
//    ['name'=>'F119','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2820.jpg'],
//    ['name'=>'F121','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2905.jpg'],
//    ['name'=>'F717','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/img_0001.JPG'],
//    ['name'=>'F122','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2839.jpg'],
//    ['name'=>'F123','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2865.jpg'],
//    ['name'=>'F671','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2015-06-20_002.JPG'],
//    ['name'=>'F716','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/img_0004.JPG'],
//    ['name'=>'F345','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/wagga-florist-010a.JPG'],
//    ['name'=>'F603','source_file'=>'http://efloristwagga.com.au/assets/galleries/60/2014-05-14_003.JPG'],
//    ['name'=>'G350','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/1wagga-florist-005.JPG'],
//    ['name'=>'G349','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/1wagga-florist-006.JPG'],
//    ['name'=>'G342','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-003a.JPG'],
//    ['name'=>'G341','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-004a.JPG'],
//    ['name'=>'G674','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2015-07-14_011.jpg'],
//    ['name'=>'G271','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-008.JPG'],
//    ['name'=>'G608','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2014-03-27_001.JPG'],
//    ['name'=>'G610','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2014-04-03_002.JPG'],
//    ['name'=>'G525','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-017.JPG'],
//    ['name'=>'G93','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/orchid_white_pink.jpg'],
//    ['name'=>'G268','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-007.JPG'],
//    ['name'=>'G92','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/9.jpg'],
//    ['name'=>'G583','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist_004.JPG'],
//    ['name'=>'G580','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist_005.JPG'],
//    ['name'=>'G672','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2015-06-19_004.JPG'],
//    ['name'=>'G389','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-013.png'],
//    ['name'=>'G581','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-020a.JPG'],
//    ['name'=>'G582','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-023a.JPG'],
//    ['name'=>'G91','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/soft_toys_4.jpg'],
//    ['name'=>'G609','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2014-03-28_003.JPG'],
//    ['name'=>'G622','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/2014-10-14_007.JPG'],
//    ['name'=>'G99','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/untitled.png'],
//    ['name'=>'G100','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/untitled0.png'],
//    ['name'=>'G165','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/gball.jpg'],
//    ['name'=>'G718','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/12-20_6_.JPG'],
//    ['name'=>'G285','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/007.JPG'],
//    ['name'=>'G287','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-002.jpg'],
//    ['name'=>'G284','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-006b.JPG'],
//    ['name'=>'G286','source_file'=>'http://efloristwagga.com.au/assets/galleries/61/wagga-florist-004.jpg']
];
$entity_image = new entity_image();
$entity_image->set(['row'=>$row]);
print_r($entity_image);
exit;